const PregnancyProfile = require('../models/PregnancyProfile');
const ANCVisit = require('../models/ANCVisit');
const Vaccination = require('../models/Vaccination');
const Medicine = require('../models/Medicine');
const cloudinary = require('../config/cloudinary');
const sendEmail = require('../config/nodemailer');
const { calculateRisk } = require('../utils/riskCalculator');

const ANC_WEEKS = [12, 20, 28, 36];
const VACCINES = ['TT1', 'TT2', 'Flu Vaccine', 'Hepatitis B'];

// ── Create or update pregnancy profile ──────────────────────────────────────
exports.createOrUpdateProfile = async (req, res) => {
    try {
        const {
            age, bloodGroup, height, weight, pregnancyWeek,
            expectedDeliveryDate, miscarriageHistory, diabetes, hypertension,
            hemoglobin, assignedDoctor,
            emergencyContactName, emergencyContactPhone, emergencyContactEmail, emergencyContactRelation,
        } = req.body;

        // BMI auto-calc
        const heightM = parseFloat(height) / 100;
        const bmi = parseFloat((parseFloat(weight) / (heightM * heightM)).toFixed(1));

        // Risk scoring
        const { score, level, factors } = calculateRisk({
            age: parseInt(age),
            hemoglobin: parseFloat(hemoglobin),
            bmi,
            diabetes: diabetes === 'true' || diabetes === true,
            hypertension: hypertension === 'true' || hypertension === true,
            miscarriageHistory: miscarriageHistory === 'true' || miscarriageHistory === true,
            pregnancyWeek: parseInt(pregnancyWeek),
        });

        const profileData = {
            mother: req.user._id,
            age: parseInt(age),
            bloodGroup,
            height: parseFloat(height),
            weight: parseFloat(weight),
            bmi,
            pregnancyWeek: parseInt(pregnancyWeek),
            expectedDeliveryDate,
            miscarriageHistory: miscarriageHistory === 'true' || miscarriageHistory === true,
            diabetes: diabetes === 'true' || diabetes === true,
            hypertension: hypertension === 'true' || hypertension === true,
            hemoglobin: parseFloat(hemoglobin),
            riskScore: score,
            riskLevel: level,
            riskFactors: factors,
            assignedDoctor: assignedDoctor || undefined,
            emergencyContact: {
                name: emergencyContactName,
                phone: emergencyContactPhone,
                email: emergencyContactEmail,
                relation: emergencyContactRelation,
            },
        };

        let profile = await PregnancyProfile.findOne({ mother: req.user._id });
        const isNew = !profile;

        if (isNew) {
            profile = await PregnancyProfile.create(profileData);
            // Scaffold ANC visits
            await Promise.all(ANC_WEEKS.map(w =>
                ANCVisit.findOneAndUpdate({ patient: req.user._id, visitWeek: w }, { patient: req.user._id, visitWeek: w }, { upsert: true, new: true })
            ));
            // Scaffold vaccinations
            await Promise.all(VACCINES.map(v =>
                Vaccination.findOneAndUpdate({ patient: req.user._id, vaccineName: v }, { patient: req.user._id, vaccineName: v }, { upsert: true, new: true })
            ));
        } else {
            Object.assign(profile, profileData);
            await profile.save();
        }

        // High-risk alert email
        if (level === 'High') {
            const doctorPop = assignedDoctor
                ? (await (require('../models/Doctor')).findById(assignedDoctor).populate('user', 'name email'))
                : null;

            const alertHtml = `
            <div style="font-family:Arial,sans-serif;padding:24px;border:2px solid #e53e3e;border-radius:12px;max-width:600px;">
              <h2 style="color:#e53e3e;">⚠️ High-Risk Pregnancy Alert — MaaCare</h2>
              <p><strong>Patient:</strong> ${req.user.name} (${req.user.email})</p>
              <p><strong>Pregnancy Week:</strong> ${pregnancyWeek}</p>
              <p><strong>Risk Score:</strong> ${score}/100</p>
              <h3 style="color:#c53030;">Risk Factors Detected:</h3>
              <ul>${factors.map(f => `<li>${f}</li>`).join('')}</ul>
              <h3 style="color:#2d3748;">Suggested Actions:</h3>
              <ul>
                <li>Schedule an urgent antenatal visit</li>
                <li>Monitor blood pressure daily</li>
                <li>Review haemoglobin and nutrition status</li>
                <li>Ensure emergency contacts are updated</li>
              </ul>
              <p style="color:#718096;font-size:13px;">This alert was auto-generated by MaaCare's Maternal Health Intelligence System.</p>
            </div>`;

            // Email to mother
            await sendEmail({ to: req.user.email, subject: '⚠️ MaaCare – High Risk Alert for Your Pregnancy', html: alertHtml });

            // Email to assigned doctor if any
            if (doctorPop?.user?.email) {
                await sendEmail({ to: doctorPop.user.email, subject: `⚠️ MaaCare – High Risk Patient Alert: ${req.user.name}`, html: alertHtml });
            }
        }

        res.status(isNew ? 201 : 200).json(profile);
    } catch (err) {
        console.error(err);
        res.status(500).json({ message: 'Server error saving pregnancy profile' });
    }
};

// ── Get own profile ──────────────────────────────────────────────────────────
exports.getProfile = async (req, res) => {
    try {
        const profile = await PregnancyProfile.findOne({ mother: req.user._id })
            .populate('assignedDoctor', 'specialistType consultationFee')
            .populate({ path: 'assignedDoctor', populate: { path: 'user', select: 'name email profileImage' } });
        if (!profile) return res.status(404).json({ message: 'Profile not found' });
        res.json(profile);
    } catch (err) {
        console.error(err);
        res.status(500).json({ message: 'Server error' });
    }
};

// ── ANC Visits ───────────────────────────────────────────────────────────────
exports.getANCVisits = async (req, res) => {
    try {
        const visits = await ANCVisit.find({ patient: req.user._id }).sort('visitWeek');
        res.json(visits);
    } catch (err) { res.status(500).json({ message: 'Error fetching ANC visits' }); }
};

exports.markANCVisit = async (req, res) => {
    try {
        const { visitWeek, notes } = req.body;
        const visit = await ANCVisit.findOneAndUpdate(
            { patient: req.user._id, visitWeek: parseInt(visitWeek) },
            { completed: true, completedDate: new Date(), notes },
            { new: true, upsert: true }
        );
        res.json(visit);
    } catch (err) { res.status(500).json({ message: 'Error updating ANC visit' }); }
};

// ── Vaccinations ─────────────────────────────────────────────────────────────
exports.getVaccinations = async (req, res) => {
    try {
        const vaccines = await Vaccination.find({ patient: req.user._id });
        res.json(vaccines);
    } catch (err) { res.status(500).json({ message: 'Error fetching vaccinations' }); }
};

exports.markVaccination = async (req, res) => {
    try {
        const { vaccineName } = req.body;
        let proofUrl = '';
        let publicId = '';
        if (req.file) {
            const result = await cloudinary.uploader.upload(req.file.path, { folder: 'maacare/vaccines' });
            proofUrl = result.secure_url;
            publicId = result.public_id;
        }
        const vaccine = await Vaccination.findOneAndUpdate(
            { patient: req.user._id, vaccineName },
            { completed: true, completedDate: new Date(), proofUrl, publicId },
            { new: true, upsert: true }
        );
        res.json(vaccine);
    } catch (err) { res.status(500).json({ message: 'Error marking vaccination' }); }
};

// ── Medicines ────────────────────────────────────────────────────────────────
exports.addMedicine = async (req, res) => {
    try {
        const med = await Medicine.create({ ...req.body, patient: req.user._id });
        res.status(201).json(med);
    } catch (err) { res.status(500).json({ message: 'Error adding medicine' }); }
};

exports.getMedicines = async (req, res) => {
    try {
        const meds = await Medicine.find({ patient: req.user._id }).sort('-createdAt');
        res.json(meds);
    } catch (err) { res.status(500).json({ message: 'Error fetching medicines' }); }
};

exports.deleteMedicine = async (req, res) => {
    try {
        await Medicine.findOneAndDelete({ _id: req.params.id, patient: req.user._id });
        res.json({ message: 'Medicine removed' });
    } catch (err) { res.status(500).json({ message: 'Error deleting medicine' }); }
};
